# Generated by Django 5.2.4 on 2025-07-05 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seguimiento1', 'Seguimiento 1'), ('seguimiento2', 'Seguimiento 2'), ('final', 'Final')], max_length=15)),
                ('contenido', models.TextField()),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('curso', models.CharField(max_length=1)),
                ('grupo', models.CharField(blank=True, max_length=15)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('num_reuniones', models.IntegerField()),
                ('temas_reuniones', models.TextField()),
                ('tipo_actividades', models.TextField()),
                ('participacion_mentorizada', models.TextField()),
                ('mejoras_sugeridas', models.TextField()),
                ('horas_dedicadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('labor_mentor', models.TextField(blank=True)),
                ('ventajas_inconvenientes', models.TextField(blank=True)),
                ('mejoras_finales', models.TextField(blank=True)),
                ('labor_mentorizado', models.TextField(blank=True)),
                ('experiencia_informada', models.TextField(blank=True)),
                ('satisfaccion', models.TextField(blank=True)),
                ('recomendacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respuesta_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
