# Generated by Django 5.2.4 on 2025-07-05 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairings', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='emparejamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='pairings.emparejamiento'),
            preserve_default=False,
        ),
    ]
