# Generated by Django 5.2.4 on 2025-07-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_informe_emparejamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='respuesta_general',
            new_name='user',
        ),
    ]
