# Generated by Django 5.2.4 on 2025-07-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_respuesta_general_informe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='participacion_mentorizada',
            new_name='participacion_mentorizada_mentor',
        ),
    ]
