# Generated by Django 5.2.4 on 2025-07-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrol',
            name='cuatrimestre',
            field=models.IntegerField(choices=[(1, 'Primer cuatrimestre'), (2, 'Segundo cuatrimestre')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudrol',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
