# Generated by Django 5.2.4 on 2025-07-05 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emparejamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cuatrimestre', models.IntegerField(choices=[(1, 'Primer cuatrimestre'), (2, 'Segundo cuatrimestre')])),
                ('fecha_emparejamiento', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emparejamientos_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emparejamientos_mentorizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mentorizado', 'year', 'cuatrimestre')},
            },
        ),
    ]
